language: minimal

services:
  - docker

script:
  - >
    docker run --rm -it -v `pwd`:/builds -u `id -u`:`id -g` hardwario/gcc-arm-embedded:latest
    make release OUT=bcf-radio-push-button-${TRAVIS_TAG} VERSION=${TRAVIS_TAG}

deploy:
  skip_cleanup: true
  file_glob: true
  file: out/release/*.bin
  api_key: ${GITHUB_KEY}
  provider: releases
  overwrite: true
  on:
    tags: true
